config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    # URL:/user/:user_id/relationships
    resource :relationships, only: [:create, :destroy]
    # フォロー一覧、フォロワー一覧へのルーティング
    # memberを書くことでURLにidが加わる。ex)/users/:id/following
    member do
      get :following, :followers
    end
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  root 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  get '/search' => 'searchs#search', as: 'search'
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
		@book_comment = BookComment.new(book_comment_params)
		@book_comment.book_id = @book.id
		@book_comment.user_id = current_user.id
    @book_comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
<h2>Comments</h2>
<table id="js-table-comment", class="table">
	<% book.book_comments.each do |book_comment|%>
		<tr id="comment-<%= book_comment.id %>">
			<td>
				<%= link_to attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg"), user_path(book_comment.user) %> <br>
				<%= book_comment.user.name %>
			</td>
			<td>
				<%= book_comment.comment %>
			</td>
			<td>
				<% if book_comment.user_id == current_user.id %>
					<%= link_to "Delete", book_book_comment_path(book,book_comment.id), method: :delete, class: "btn-sm btn-danger",remote: true %>
				<% end %>
			</td>
		</tr>
	<% end %>
</table>

app/views/book_comments/_comment_form.html.erb
<%= form_with(model:[book, book_comment], remote: true) do |f| %>
	<div class="row">
    	<div class="col-sm-12">
      		<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
		</div>
  	</div>
  	<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/book_comments/create.js.erb
<!--id="book-<%= @book.id %>-comment-count"の部分（コメント数）の部分的更新を行う。-->
$("#book_<%= @book.id %> .comments-count").html("コメント数：<%= @book.book_comments.count %>");
<!--id="#book-comment-<%= @book.id %>"の部分をrenderで部分的更新を行う。-->
$("#book-comment-<%= @book.id %>").html("<%= j(render partial: 'comment', locals: {book: @book} )%>");
<!--エラーメッセージがある場合は、エラーメッセージを部分的更新を行う。-->
$("#error_explanation").html("<%= j(render 'layouts/errors', { obj: @book_comment }) %>");
<!--コメント入力フォームの中身を空にする。-->
$('#book_comment_comment').val("");

app/views/book_comments/destroy.js.erb
<!--id="book-<%= @book.id %>-comment-count"の部分（コメント数）の部分的更新を行う。-->
$("#book_<%= @book.id %> .comments-count").html("コメント数：<%= @book.book_comments.count %>");
<!--id="#book-comment-<%= @book.id %>"の部分をrenderで部分的更新を行う。-->
$("#book-comment-<%= @book.id %>").html("<%= j(render partial: 'comment', locals: {book: @book} )%>")
<!--エラーメッセージが出ている状態で削除した時に、エラーメッセージを非表示にするため。-->
$("#error_explanation").html("<%= j(render 'layouts/errors', { obj: @book }) %>")