config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    # URL:/user/:user_id/relationships
    resource :relationships, only: [:create, :destroy]
    # フォロー一覧、フォロワー一覧へのルーティング
    # memberを書くことでURLにidが加わる。ex)/users/:id/following
    member do
      get :following, :followers
    end
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  root 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  get '/search' => 'searchs#search', as: 'search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :
  
  include JpPrefecture
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  # フォローする側のリレーションシップ
  has_many :active_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  # N：Nのリレーションシップにはthroughを使う。user.following = user.followed.idとなるようにsourceを設定
  has_many :following, through: :active_relationships, source: :followed

  # フォロワーのリレーションシップ
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :followed_id
  # N：Nのリレーションシップにはthroughを使う。user.followers = user.follower.idとなるようにsourceを設定
  has_many :followers, through: :passive_relationships, source: :follower
  
  # 他パラメータ
  # 画像を設定できるようにする
  attachment :profile_image, destroy: false
  # 都道府県コードから都道府県名に自動で変換する
  jp_prefecture :prefecture_code
  
  #バリデーションチェック 
  validates :name,length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}
  
  #メソッド 
  #すでにフォロー済みであればture返す
  def following?(other_user)
    following.include?(other_user)
  end
  
  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  # ユーザーを検索し、結果を返す
  def self.search_for(content, how)
    if how == 'perfect'
      User.where(name: content)
    elsif how == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif how == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
  
  # @user.prefecture_nameで該当ユーザーの住所(都道府県)を表示出来るようにする
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end
  
  def following
    # フォロー一覧を表示するユーザをインスタンス変数に格納し、引き渡す。
    @user  = User.find(params[:id])
  end

  def followers
    # フォロワー一覧を表示するユーザをインスタンス変数に格納し、引き渡す。
    @user  = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <!--follows-->
  			<td>フォロー数：<%= user.following.count %></td>
  			<!--followers-->
  			<td>フォロワー数：<%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<!--follows-->
	<tr>
		<th>follows</th>
		<!--フォロー一覧画面へのリンク-->
		<th><%= link_to user.following.count, following_user_path(user)  %></th>
	</tr>
	<!--followers-->
	<tr>
		<th>followers</th>
		<!--フォロワー一覧画面へのリンク-->
		<th><%= link_to user.followers.count, followers_user_path(user)  %></th>
	</tr>
</table>

<div class="row">
	<% if user.id == current_user.id %>
		<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	<% else %>
		<!--<%= link_to '', user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>-->
	<% end %>
</div>
<!--他ユーザのプロフィールの場合-->
<% if user.id != current_user.id %>
	<!--フォローしている場合（カレントユーザのフォロー一覧の中に現在のユーザが含まれていた場合）-->
    <% if current_user.following?(user) %>
        <%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn-sm btn-danger" %>
    <!--フォローしていない場合（カレントユーザのフォロー一覧の中に現在のユーザが含まれていない場合）-->
    <% else %>
        <%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn-sm btn-success" %>
    <% end %>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_with model:@user, local: true do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<% if @user.followers.count != 0 %>
    <%= render 'users/index', users: @user.followers %>
<% else %>
    <p>ユーザはいません。</p>
<% end %>

app/views/users/following.html.erb
<h2>Follow Users</h2>
<% if @user.following.count != 0 %>
	<%= render 'users/index', users: @user.following %>
<% else %>
    <p>ユーザはいません。</p>
<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="4"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name %></td>
					<!--follows-->
					<td>フォロー数：<%= user.following.count %></td>
					<!--followers-->
					<td>フォロワー数：<%= user.followers.count %></td>
					<!--フォロー、フォロー解除ボタンの設置-->
					<!--フォローしている場合-->
					<td>
					    <!--他ユーザの場合-->
						<% if user.id != current_user.id %>
							<!--フォローしている場合（カレントユーザのフォロー一覧の中に現在のユーザが含まれていた場合）-->
						    <% if current_user.following?(user) %>
						        <%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn-sm btn-danger" %>
						    <!--フォローしていない場合（カレントユーザのフォロー一覧の中に現在のユーザが含まれていない場合）-->
						    <% else %>
						        <%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn-sm btn-success" %>
						    <% end %>
						<% end %>
				    </td>
					<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--users一覧 -->
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<%= render 'books/index', books: @books %>
		<!--books一覧 -->
	</div>
</div>