config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    # URL:/user/:user_id/relationships
    resource :relationships, only: [:create, :destroy]
    # フォロー一覧、フォロワー一覧へのルーティング
    # memberを書くことでURLにidが加わる。ex)/users/:id/following
    member do
      get :following, :followers
    end
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  root 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  get '/search' => 'searchs#search', as: 'search'
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	# いいねをしているかを判定する
	def favorited_by?(user)
	    favorites.where(user_id: user.id).exists?
	end
	
	# Bookを検索し、結果を返す
	def self.search_for(content, how)
	    if how == 'perfect'
	    	Book.where(title: content)
	    elsif how == 'forward'
	    	Book.where('title LIKE ?', content+'%')
	    elsif how == 'backward'
	    	Book.where('title LIKE ?', '%'+content)
	    else
	    	Book.where('title LIKE ?', '%'+content+'%')
	    end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_current_user, {only: [:edit, :update, :destroy]}

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_current_user
    @book = Book.find(params[:id])
    # @current_user = current_user
    if current_user.id != @book.user_id
      flash[:notice]="権限がありません"
      redirect_to  books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body' %>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th>Good</th>
			<th>Comment</th>
			<th colspan="1"></th>
		</tr>
	</thead>

	<tbody>
		<% books.each do |book| %>
			<tr>
				<td>
					<%= link_to user_path(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
					<% end %>
				</td>
				<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
				<td><%= book.body %></td>
				<td>
					<div id="favorites_buttons_<%= book.id %>">
						<%= render partial: 'favorites/favorite', locals: { book: book} %>
					</div>
				</td>
				<td>
					<i class="fa fa-comment"></i>
					コメント数：<%= book.book_comments.count %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/books/edit.html.erb
<div class="row">
	<%= render "layouts/errors", obj: @book %>
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<%= render "books/form", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<%= render "layouts/errors", obj: @book %>
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>
	</div>
	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<%= render 'books/index', books: @books %>
		<!--books一覧 -->
	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div id="error_explanation">
		<%= render "layouts/errors", obj: @book_comment %>
	</div>
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @book.user %>

		<h2>New book</h2>
		<%= render 'books/form', book: Book.new %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
			<tr id="book_<%= @book.id %>">
				<td>
					<%= link_to user_path(@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
					<%= @book.user.name %>
					<% end %>
				</td>
				<td><%= link_to @book.title, book_path(@book) %></td>
				<td><%= @book.body %></td>
				<!--いいね数の表示-->
				<td>
					<div id="favorites_buttons_<%= @book.id %>">
						<%= render partial: 'favorites/favorite', locals: { book: @book} %>
					</div>
				</td>	
				<!--いいね数の表示ここまで-->
				<!--コメント数の表示-->
				<td>
				  	<i class="fa fa-comment"></i>
			  		<div class="comments-count">
			  			コメント数：<%= @book.book_comments.count %>
			  		</div>
				</td>
				<!--コメント数の表示ここまで-->
				<% if @book.user.id == current_user.id %>
					<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
				<% end %>
			</tr>
		</table>
		<!--コメント一覧-->
		<div id="book-comment-<%= @book.id %>">
			<%= render 'book_comments/comment', book: @book %>
		</div>
		<!--コメント一覧ここまで-->
		<!--コメント入力フォーム-->
		<%= render 'book_comments/comment_form', book: @book, book_comment: @book_comment %>
		<!--コメント入力フォームここまで-->
	</div>
</div>